name: lpinyin
description: Chinese character conversion pinyin library.Accurate and complete Chinese character dictionary.Fast conversion.
version: 1.1.1
author: Sky24n <sky24no@gmail.com>
homepage: https://github.com/flutterchina/lpinyin

environment:
  sdk: ">=1.19.0 <3.0.0"